### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by MXC48-zz** [woheller69/lavatories#1]
Please add the project in Crowdin or Weblate platform, I would like to participate by translating into French...

**Comment by woheller69** [comment]
Just translate this file

https://github.com/woheller69/lavatories/blob/master/app/src/main/res/values/strings.xml

Maybe there are some unused strings from my weather or gas prices app. Need to clean up code...

**Comment by le-jun** [comment]
Could you provide further instructions for localization? Should one send you a translated file, add to the existing one using tags or else?

**Comment by woheller69** [comment]
just a translated file is enough

**Comment by le-jun** [comment]
[Here you go!](https://github.com/woheller69/lavatories/files/9486918/strings_fr.txt)

**Comment by woheller69** [comment]
Please try. Remove .zip and install (uninstall F-droid version first)

[app-release.apk.zip](https://github.com/woheller69/lavatories/files/9488723/app-release.apk.zip)

**Comment by le-jun** [comment]
Ha, I can’t test anything. My phone is too old for those kind of uses, memory is fully occupied by system files.

**Comment by woheller69** [comment]
->V1.1
