### ISSUE TITLE
UI Improvement suggestion

### ISSUE THREAD

**Issue by Kouzola** [woheller69/lavatories#10]
Hi,

I use this app and it's a good app. I have a suggestion that can be useful. It would be great if we can see on what item we clicked when we select a toilet. Because sometimes, I click on a toilet and the circle appear on the map but then I forget about what toilet I select in the recyclerView. We can do this by changing the background color by example.

If you think it's a good idea, I can do it if it's possible.

**Comment by woheller69** [comment]
Please try.

Uninstall
Remove .zip and install

[app-release.apk.zip](https://github.com/woheller69/lavatories/files/12266253/app-release.apk.zip)

**Comment by woheller69** [comment]
Another fix

[app-release.apk.zip](https://github.com/woheller69/lavatories/files/12266265/app-release.apk.zip)

**Comment by Kouzola** [comment]
Yes it's working fine.

Well done.
