### ISSUE TITLE
Feature request: Find location by network

### ISSUE THREAD

**Issue by bege10** [woheller69/lavatories#11]
Hello,
this app is a great idea! Thank you!
Currently it finds the location only by GPS. Depending on the current location this may take a long time while other apps already found the location by network. Can you add this feature?
Fairphone 3, /e/OS (based on LineageOS for microG, Android 11)

**Comment by woheller69** [comment]
For privacy reasons this app only uses GPS. Other location providers need external services to lookup location.

**Comment by bege10** [comment]
I see. I have /e/OS on my phone (microG with UnifiedNLP instead of Google services), it only uses the Mozilla database. Maybe you could add it as an option so users can decide whether to allow it?

**Comment by woheller69** [comment]
Network provider is usually not very exact, so probably it is worth waiting a few seconds more to get a precise location.
The next version (see #12) will also show your current position with a moving icon on the map
