### ISSUE TITLE
The current location point is not displayed

### ISSUE THREAD

**Issue by Korb** [woheller69/lavatories#12]
**Describe the bug**
I don't see my location marker on the map.  Accordingly, I cannot evaluate which of the nearest found places is more convenient for me to choose.

**How to Reproduce**
1. Enable GPS on your smartphone
2. Launch the LavSeeker, granting it the permissions it requested.

**Expected behavior**
The map always shows a marker for my location.  When you click on the corresponding interface button, the map moves so that the mark is in the center of the map window.

**Screenshots**
![Screenshot_20230816_093753](https://github.com/woheller69/lavatories/assets/3509797/e09b7b70-75d2-4dfc-ab68-eb0309794827)

**Environment (please complete the following information):**
 - App version: v1.8
 - Android version: 13
 - Device: Vivo T1 4G

OS version: Funtouch OS 13 Global
Model: V2153
Hardware version: MP_0.1
Build number: PD22010F_EX_A_13.1.15.4.W20.V000L1
Baseband version: MPSS.HA.1.1.c2-00012-KD_ALL_PACK-1.6347.102
Kernel version: 4.19.157-perf+. 1 Tue Jul 4 17:48:44 CST 2023
Compile time: 4 Jul 2023 12:28:54
Android security update: 1 July 2023
Google Play system update: 1 July 2023

**Comment by woheller69** [comment]
you can try this

Uninstall
Remove .zip 
Install

[app-release.apk.zip](https://github.com/woheller69/lavatories/files/12359229/app-release.apk.zip)

**Comment by Korb** [comment]
> [app-release.apk.zip](https://github.com/woheller69/lavatories/files/12359229/app-release.apk.zip)

In this version, the current location is correctly displayed with a red mark. I would like to see the same in the official release on F-Droid.

**Comment by woheller69** [comment]
I just implemented this feature...
