### ISSUE TITLE
Toilets without their own POI are not displayed

### ISSUE THREAD

**Issue by impeira** [woheller69/lavatories#13]
Unfortunately I don't see the toilets which don't have their own POIs, but are tagged within another amenity entries, like libraries and other public buildings.

It would be great if these toilets are also shown.

**Comment by woheller69** [comment]
This app searches for amenity=toilets.
If they are not tagged correctly they will not be shown.
Toilets which are tagged with access = private are discarded.

**Comment by impeira** [comment]
In the osm wiki it says:

"Facilities such as shops and pubs often have toilets inside them for customers, and sometimes free for the public as part of a scheme (e.g. Richmond Council). On the usual tags of amenity=pub, building=yes, shop=* add the following tags and use the 'toilets' namespace." https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtoilets

So I would assume to find also these toilets in the app.

**Comment by woheller69** [comment]
As the description (for people editing OpenStreetMap) says someone needs to "add" these tags. 
If they are not tagged in OpenStreetMap LavSeeker cannot find them.
You can contribute by tagging such toilets in OpenStreetMap (https://www.openstreetmap.org/edit)

**Comment by impeira** [comment]
Yes and I do sometimes. That's the reason I am asking.
E.g.: https://www.openstreetmap.org/node/277834166

Previously it was only tagged with toilets:wheelchair=yes, now (since 6 days) also with toilets=yes and toilets:access=public.

But in lavatories I don't see these. What am I doing wrong?

**Comment by woheller69** [comment]
I don't know if such toilets are found via the overpass-api which I am using.
They need to be tagged as amenity=toilets

**Comment by woheller69** [comment]
But I think such "real" public toilets  should have a separate POI.
If I included all toilets in places via a separate search for "toilets=yes" this would also show all toilets in restaurants, shops etc which are usually not meant to be public but only for customers.

**Comment by woheller69** [comment]
Will think about a switch in settings

**Comment by woheller69** [comment]
Please try this:
[app-release.apk.zip](https://github.com/woheller69/lavatories/files/12386628/app-release.apk.zip)
-Uninstall
-Remove .zip and install

This version also shows toilets which are:
- tagged as "toilets = yes"
- not tagged as "access = customers" or "access = no"

**Comment by impeira** [comment]
Looking good.

Now I notice that 'only' 50 entries are shown. It would be great if there were some sort of filter (e.g. show only POIs which are open at the time) or hide POIs without enough information (operator is missing etc.).

**Comment by woheller69** [comment]
opening hours are only given as text, nothing that can be simply evaluated, maybe with AI.
Operator is often missing for public toilets, but they are still there...

**Comment by woheller69** [comment]
In this version you can click on a toilet on the map and it will scroll to the details

[app-release.apk.zip](https://github.com/woheller69/lavatories/files/12387429/app-release.apk.zip)

**Comment by impeira** [comment]
The other way around would also be great. So if I click at an entry from the list, it zooms to the place on the map.
One other 'killer' feature I miss is to navigate (and zoom) to my current gps position.

**Comment by woheller69** [comment]
if you click on an item on the list it highlights the element on the map, it just does not zoom.

if you have GPS allowed in settings, your position will be shown with a red marker on the map and if you click on the location icon in the actionbar your current position will be used as center position and toilets around your position will be searched

**Comment by impeira** [comment]
` it just does not zoom.`
Yes, but that only works, if I previously haven't zoomed in and scrolled to see a more detailed map. Otherwise I often do not see the entry I clicked.

`if you have GPS allowed in settings`
Ah sorry, wasn't aware that by default it is disabled.

**Comment by woheller69** [comment]
This version even shows toilets which are not tagged as "node" but as "way" which is true for quite many...

[app-release.apk.zip](https://github.com/woheller69/lavatories/files/12388059/app-release.apk.zip)

**Comment by woheller69** [comment]
Done

**Comment by woheller69** [comment]
Done
