### ISSUE TITLE
Ability to open a note

### ISSUE THREAD

**Issue by dpriskorn** [woheller69/lavatories#15]
Hi, I would like to open a note if the lavatory is missing opening hours or similar.

**Comment by woheller69** [comment]
In next version a long click on an item will open the entry on OpenStreetMap if "debug" is enabled in settings.
There you can log in and modify

**Comment by woheller69** [comment]
You can try it here

Uninstall
Remove .zip and install
Switch on "debug" in settings
Long click on entry in list

[app-release.apk.zip](https://github.com/woheller69/lavatories/files/12615783/app-release.apk.zip)
