### ISSUE TITLE
Integration with everydoor

### ISSUE THREAD

**Issue by dpriskorn** [woheller69/lavatories#16]
I would like to be able to easily jump to the position of a toilet in everydoor if possible.

**Comment by woheller69** [comment]
as far as I see Every Door does not have an intent filter for that purpose

**Comment by dpriskorn** [comment]
I'll suggest to them to support this use case then.

**Comment by woheller69** [comment]
Ideally they should react on URLs like:

https://www.openstreetmap.org/node/966313875
https://www.openstreetmap.org/way/38300952
