### ISSUE TITLE
Allow zooming using two fingers on the map instead of +/- buttons

### ISSUE THREAD

**Issue by m0byn** [woheller69/lavatories#17]
**Describe the bug**
It is not possible to zoom in and out on the map using two fingers. Only by using the +/- buttons

**How to Reproduce**
1. Open the app
2. Go to toilets
3. Try to zoom in and out on the map
4. See that it is only possible by +/- buttons

**Expected behavior**
Allow zooming by using the fingers.

**Environment (please complete the following information):**
 - App version: v2.2
 - Android version: 13
 - Device: Samsung Galaxy A52s 5G running LineageOS 20 (officially supported)

**Comment by woheller69** [comment]
Will remove the buttons in future and replace with multi touch controls.
Please try.

-Uninstall
-Remove .zip and install

[app-release.apk.zip](https://github.com/woheller69/lavatories/files/13708189/app-release.apk.zip)

**Comment by m0byn** [comment]
Perfect! Works :)
