### ISSUE TITLE
Can't insert location

### ISSUE THREAD

**Issue by skariko** [woheller69/lavatories#2]
**Describe the bug**

Can't add any location

**How to Reproduce**

Try to add location.
Enter name of a location and nothing happen.

**Screenshots**

https://user-images.githubusercontent.com/25532821/188270100-33b1cb5b-3a02-4662-b7d6-0da0b9c40de3.mp4

**Environment (please complete the following information):**
 - App version: 1.0
 - Android version: 13
 - Device: Google Pixel 6

**Comment by woheller69** [comment]
Cannot test that. Probably an Android 13 issue. Works well on Android 12 and below

**Comment by woheller69** [comment]
Can you try this version? Remove .zip and install (uninstall other version before)

This version should show an error message if retrieving the locations is not working
[app-release.apk.zip](https://github.com/woheller69/lavatories/files/9485217/app-release.apk.zip)

**Comment by skariko** [comment]
> Can you try this version? Remove .zip and install (uninstall other version before)
> 
> This version should show an error message if retrieving the locations is not working [app-release.apk.zip](https://github.com/woheller69/lavatories/files/9485217/app-release.apk.zip)

Yes it give me this error: `com.android.volley.ClientError`

**Comment by woheller69** [comment]
No idea, must be an Android 13 issue. Can you provide logcat output?

**Comment by skariko** [comment]
> No idea, must be an Android 13 issue. Can you provide logcat output?

How can I do that?

**Comment by woheller69** [comment]
you need a PC and Android platform tools. Then you can get a logcat via 

adb logcat -d > logcat.txt
