### ISSUE TITLE
Play system warning when installing??

### ISSUE THREAD

**Issue by twizzlebizzle** [woheller69/lavatories#20]
**Describe the bug**
Play system protect from Google sees this app as harmful, I've installed tonnes of fdroid and APK files and this is the only app I've seen it on.

**How to Reproduce**
1. Install via fdroid or droidify
2. This warning comes up, why?

**Expected behavior**
Play protect shouldn't see it as harmful?

**Screenshots**
![Screenshot_20240406-211539](https://github.com/woheller69/lavatories/assets/11423542/643abd24-a75c-441d-a9c6-7a4218c03475)

**Environment (please complete the following information):**
 - App version: 2.3
 - Android version: 14 April patch
 - Device: Pixel 7 Pro

**Comment by woheller69** [comment]
Nothing I can change. Play Protect is the bug.

**Comment by woheller69** [comment]
"This app collects data that could be used to track you" is correct, of course. Like any app that uses GPS.

**Comment by PanderMusubi** [comment]
> "This app collects data that could be used to track you" is correct, of course. Like any app that uses GPS.

But that is also the case for maps.me and osmand. Is there a reason why Play Protect is triggered in this case?

**Comment by woheller69** [comment]
no it's just a stupid Google warning protecting you from stuff they don't make money from.

I always switch it off...
