### ISSUE TITLE
Configurable filter

### ISSUE THREAD

**Issue by opk12** [woheller69/lavatories#22]
Thank you for making LavSeeker and DumpSeeker. What about a generic app, where the user configures the POI filter?

For example, the Italian OSM community discussed a drinking water map today, but asking for yet another specialized app seemed excessive.

**Comment by woheller69** [comment]
unfortunately it is not that simple.
Different amenities also have different properties and you also need different icons.
e.g. a lavatory can have a baby changing table as property, a drinking water place will not have that.
