### ISSUE TITLE
Feature request: Use Gps without the need to add location

### ISSUE THREAD

**Issue by motey** [woheller69/lavatories#3]
Thanks for the project ♥️
As far as i see, i need to manually add any location first to be able to use the current location button. When traveling a lot, a fixed position does not make sense. 
The possibility to always (and only) use the current position without the need to manually add a fixed position beforehand would be great

**Comment by woheller69** [comment]
you only need to add any position once. Then you can always update it, just don't delete it.

**Comment by motey** [comment]
Ok, thanks for the information. this is not very intuitive from a user perspective but works for now :)

**Comment by woheller69** [comment]
Please try this. Uninstall old version. Download this version and remove .zip
Install.

If no city is defined a click on the location icon (only available if GPS is allowed in settings) will add an empty city and get its location

[LavSeeker.apk.zip](https://github.com/woheller69/lavatories/files/9640291/LavSeeker.apk.zip)

**Comment by woheller69** [comment]
Some bugfixes

[LavSeeker.apk.zip](https://github.com/woheller69/lavatories/files/9640772/LavSeeker.apk.zip)

**Comment by motey** [comment]
Thanks for the effort.
Removed my current installation from fdroid and installed [this apk](https://github.com/woheller69/lavatories/issues/3#issuecomment-1257187073)

Still the same behaviour. I start the app, expect to find lavatories around me but the app wants me to select a city first. i go to locations and click on the location+ icon and the app wants me to type in a city name (an empty string is denied)

**Comment by woheller69** [comment]
If you activate GPS in settings, the app will show the location icon. Click on it to add current location

**Comment by motey** [comment]
hihi, ok got it. it works now.
but as feedback: it is still a little bit cumbersome compared to other apps i experienced. i would expect the app asking me for the permission when clicking on the current location icon instead of having to enable it in the settings first.

**Comment by woheller69** [comment]
I know. It is a privacy friendly app, so I do not want to request lots of permissions. Maybe I will change this in future
