### ISSUE TITLE
When the app asks if I like it, I star "spritpreise" instead of "lavatories"

### ISSUE THREAD

**Issue by DamageIncorporated** [woheller69/lavatories#4]
**Describe the bug**
Just a glitch: The app asks to star it on github. When I click the button, it drops me on the wrong project: spritpreise

**How to Reproduce**
1. Wait for the app to ask if you like it
2. select "star on github"
4. project page of "spritpreise" is opened instead of "lavatories"

**Expected behavior**
Link to lavatories project page ;-)

**Comment by woheller69** [comment]
Thanks, will be changed in next version
