### ISSUE TITLE
Just an appreciation post

### ISSUE THREAD

**Issue by domportera** [woheller69/lavatories#5]
Just wanted to stop by and let you know that this app gives me so much faith in humanity and can be absolutely invaluable for so many people. I certainly know it's come in handy for me. It's for real a shining example of free software doing what it does best

I know that sounds dramatic considering how it's a bathroom seeker but for people who are homeless or otherwise in a state of urgency away from home, this helps solve a huge public good in a user friendly way. especially in places where public bathrooms are hard to come by or spot (most of the US). it's a problem a lot of people don't pay much mind to

so, with absolutely no caveats, thank you for making one of my favorite apps. I hope you understand the value of what you do and that other people catch on and make use of it as well.

**Comment by woheller69** [comment]
Thanks a lot. But off course this app is only possible because of the many people contributing to OpenStreetMap.
Everyone can help make this app better by adding / correcting the entries (Toilet POIs) in OpenStreetMap.
