### ISSUE TITLE
New Logo Suggestion

### ISSUE THREAD

**Issue by SecularSteve** [woheller69/lavatories#6]
Came up with it myself in Inkscape... All SVG assets used are from "SVG Repo" under the CC0 licence.

ZIP contains all SVGs used to make these, and PNG variations previewed below.

[LavSeeker_logo.zip](https://github.com/woheller69/lavatories/files/9889897/LavSeeker_logo.zip)

![LavSeeker_logo](https://user-images.githubusercontent.com/33793273/198677394-f17abcb1-ba0a-4e1b-99a0-4cb9fa5c935e.png)
![LavSeeker_logo_round](https://user-images.githubusercontent.com/33793273/198677397-4480ccc6-12e2-42c7-b659-30934d4ceb3f.png)
![LavSeeker_logo_solid](https://user-images.githubusercontent.com/33793273/198677398-a087c3ab-71cc-4826-a3bd-0ed751020f1d.png)
![LavSeeker_logo_solid_mono](https://user-images.githubusercontent.com/33793273/198677401-989ceecd-e268-4d27-bda3-29a2d2a347ac.png)
![LavSeeker_logo_solid_mono_white](https://user-images.githubusercontent.com/33793273/198677402-8b0d90fe-12de-4a92-92a2-21e40fee2ab4.png)
![LavSeeker_logo_solid_round](https://user-images.githubusercontent.com/33793273/198677404-0b2b687b-4bf6-419e-9af9-9aa9023f6fbd.png)
![LavSeeker_logo_solid_round_mono](https://user-images.githubusercontent.com/33793273/198677407-af2b4f65-3627-4ecc-bdff-ae8d62597d34.png)
![LavSeeker_logo_solid_round_mono_white](https://user-images.githubusercontent.com/33793273/198677410-02aead76-3be5-40dc-b8cc-26ede6e57044.png)

**Comment by woheller69** [comment]
Thanks for the proposal, will think about it.
What is the "SVG Repo"?

**Comment by SecularSteve** [comment]
This:
https://www.svgrepo.com/

**Comment by woheller69** [comment]
will be in next release
