### ISSUE TITLE
German special symbols are displayed incorrectly

### ISSUE THREAD

**Issue by rvs2000** [woheller69/lavatories#7]
![Screenshots_2023-01-10-17-30-16](https://user-images.githubusercontent.com/353182/211608177-e12168c8-372c-4259-8bae-bc17f6444f24.png)

for example: Ü -> ZÜRIWC (see screenshot)

**Comment by woheller69** [comment]
please try this.
Uninstall old app.
Remove .zip
Install

[app-release.apk.zip](https://github.com/woheller69/lavatories/files/10385852/app-release.apk.zip)

**Comment by rvs2000** [comment]
Perfect
