### ISSUE TITLE
Error when trying to retrieve location using photon

### ISSUE THREAD

**Issue by margerber** [woheller69/lavatories#8]
com.android.volley.NoConnectionError: java.io.IOException: unexpected end of stream on com.adnroid. ok. http.Address@7f2e8
I'm on lineageos 17.1.
I reckon it has to do with photon requesting the locations via unencrypted http?

**Comment by woheller69** [comment]
they sometimes seem to have problems with their response times.

Then usually their website does not work either.
https://photon.komoot.io/

The app uses https for the call.
Should work again later. You can use GPS to get your position

**Comment by margerber** [comment]
I see. Thanks for the prompt reply!
