### ISSUE TITLE
Add Apks to releases

### ISSUE THREAD

**Issue by einekratzekatze** [woheller69/lavatories#9]
I personally rather install stuff using obtainium directly than installing from fdroid, so adding the apks would be nice

**Comment by woheller69** [comment]
you can also update from F-Droid via Obtainium

**Comment by einekratzekatze** [comment]
> you can also update from F-Droid via Obtainium

The Issue isn't how I obtain apps, but where I obtain them from.
To understand why I want to avoid F-Droid [this](https://madaidans-insecurities.github.io/android.html) sums it up pretty well.
So I would greatly appreciate apk builds attached to the releases

Without looking into it too deep [Accresecent](https://accrescent.app) also seems to be solid alternative for F-Droid.

**Comment by woheller69** [comment]
I don't see why this is a case against F-Droid. F-Droid is the safest place where you can get your apps from.

**Comment by einekratzekatze** [comment]
> I don't see why this is a case against F-Droid. F-Droid is the safest place where you can get your apps from.

I am unsure how you get to that conclusion based of the article, but I don't think it helps fighting about it.
I'll just ask you again to add the apk to the releases, as I would greatly appreciate it, but if you don't want to I'll have to deal with that.

**Comment by woheller69** [comment]
F-Droid is not even  mentioned in that article, so why is it a problem?

**Comment by einekratzekatze** [comment]
> F-Droid is not even mentioned in that article, so why is it a problem?

I've sent you the wrong one, I am soo sorry 😥
https://privsec.dev/posts/android/f-droid-security-issues/
I mean this one

**Comment by m0byn** [comment]
As I use Obtainium too I would greatly appreciate having APKs provided in the releases section! This would be the only app I would have to install from F-Droid, so I would appreciate APKs to finally uninstall F-Droid from my phone.
